In [1]:
import numpy as np

In [2]:
arr=np.array([11,22,33,44,55,66,77])

In [3]:
print("Datatype ", type(arr))
print("Value ", arr)
print("Num of dimensions ", arr.ndim)
print("Size of each dimension ", arr.shape)
print("Value at index 5 ", arr[5])


Datatype  <class 'numpy.ndarray'>
Value  [11 22 33 44 55 66 77]
Num of dimensions  1
Size of each dimension  (7,)
Value at index 5  66


In [4]:
arr

array([11, 22, 33, 44, 55, 66, 77])

In [5]:
arr.50

SyntaxError: invalid syntax (<ipython-input-5-9815ee2a4ec1>, line 1)

In [6]:
arr>50

array([False, False, False, False,  True,  True,  True])

In [7]:
np.where(arr>50)

(array([4, 5, 6], dtype=int64),)

In [9]:
arr[arr>50]

array([55, 66, 77])

In [10]:
arr*100


array([1100, 2200, 3300, 4400, 5500, 6600, 7700])

In [11]:
arr/10

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7])

In [67]:
np.round(arr/100,3)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19])

In [68]:
a1=np.arange(10)

In [69]:
a2=np.arange(10)

In [16]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
print(a2)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a1*a2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
a1+a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
a1-a2


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# boolean---.int------>float--------------.> string

In [76]:
mArr=np.array([11,22,33,44,True,76.4,'s'])

In [83]:
mArr[3:]

array(['44', 'True', '76.4', 's'], dtype='<U32')

In [78]:
mArr

array(['11', '22', '33', '44', 'True', '76.4', 's'], dtype='<U32')

# Finance Data Analysis

In [53]:
# input data
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]

expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [54]:
revenue=np.array(revenue)

In [55]:
expenses= np.array(expenses)

In [56]:
#- profit for each month
profit=revenue-expenses
print(profit)

[ 2522.67  1911.39 -3707.79 -2914.31  -599.92  7265.24  8210.55  3944.97
  3328.39 -2238.65   659.6  11629.54]


In [57]:
#- profit after tax for each month (the tax rate is 30%)
profit_tax=profit-profit*0.3

In [58]:
print(profit_tax)

[ 1765.869  1337.973 -2595.453 -2040.017  -419.944  5085.668  5747.385
  2761.479  2329.873 -1567.055   461.72   8140.678]


In [46]:
#- profit margin for each month - equals to profit after tax divided by revenue
print(profit_tax/revenue)


[ 0.12116163  0.17589956 -0.30139698 -0.22233524 -0.05211096  0.62743886
  0.49993433  0.28276199  0.22608449 -0.10897492  0.04309514  0.52746804]


In [40]:
#- good months - where the profit after tax was greater than the mean for the year
print(profit_tax>profit.mean())


[False False False False False  True  True  True False False False  True]


In [42]:
#- bad months - where the profit after tax was less than the mean for the year

print(profit_tax<profit.mean()
     )


[ True  True  True  True  True False False False  True  True  True False]


In [60]:
#- the best month - where the profit after tax was max for the year
print(profit_tax.max())

#second method




8140.678000000001


In [44]:
#- the worst month - where the profit after tax was min for the year

print(profit_tax.min())

-2595.4530000000004


In [50]:
profit_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [61]:
profit_tax==profit_tax.max()



array([False, False, False, False, False, False, False, False, False,
       False, False,  True])

In [62]:
profit_tax==profit_tax.min()

array([False, False,  True, False, False, False, False, False, False,
       False, False, False])

 # numpy 2d arrays

In [84]:
arr = np.arange(20)
m1 = np.reshape(arr, (5,4))
m2 = arr.reshape((5,4))


In [85]:
m1/m2

C:\Users\sravillu.ORADEV\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [86]:
mDiv=np.nan_to_num(m1/m2)
print(mDiv.max(),mDiv.min(),mDiv.mean())


1.0 0.0 0.95


C:\Users\sravillu.ORADEV\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [87]:
mDiv

array([[0., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])